image: golang:1.9

before_script:
  - mkdir -p /go/src/gitlab.daplie.com/
  - cp -r /builds/core-sdk /go/src/gitlab.daplie.com/core-sdk
  - cd /go/src/gitlab.daplie.com/core-sdk/hyperdht
  - go env # Just because the output can be helpful
  - go get -d -t ./...

coverage:
  script: "bash -euc '
    mkdir -p cover;
    PKG_LIST=$(go list ./... | grep -v -e \"/cmd/\" -e \"internal/protoSchemas\");
    for pkg in ${PKG_LIST}; do
      go test $pkg -covermode=count -coverprofile cover/${pkg##*/}.out -timeout 2m -v;
    done;

    echo \"mode: count\" > cover/total.cov;
    tail -q -n +2 cover/*.out >> cover/total.cov;
    go tool cover -func=cover/total.cov;
  '"

race:
  script: go test ./... -race -timeout 5m -v
