// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package hyperdht

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerRequest struct {
	Type                 *uint32  `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Port                 *uint32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	LocalAddress         []byte   `protobuf:"bytes,3,opt,name=localAddress" json:"localAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerRequest) Reset()         { *m = PeerRequest{} }
func (m *PeerRequest) String() string { return proto.CompactTextString(m) }
func (*PeerRequest) ProtoMessage()    {}
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_1b1d20431b205818, []int{0}
}
func (m *PeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerRequest.Unmarshal(m, b)
}
func (m *PeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerRequest.Marshal(b, m, deterministic)
}
func (dst *PeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerRequest.Merge(dst, src)
}
func (m *PeerRequest) XXX_Size() int {
	return xxx_messageInfo_PeerRequest.Size(m)
}
func (m *PeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerRequest proto.InternalMessageInfo

func (m *PeerRequest) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *PeerRequest) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *PeerRequest) GetLocalAddress() []byte {
	if m != nil {
		return m.LocalAddress
	}
	return nil
}

type PeerResponse struct {
	Peers                []byte   `protobuf:"bytes,1,opt,name=peers" json:"peers,omitempty"`
	LocalPeers           []byte   `protobuf:"bytes,2,opt,name=localPeers" json:"localPeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerResponse) Reset()         { *m = PeerResponse{} }
func (m *PeerResponse) String() string { return proto.CompactTextString(m) }
func (*PeerResponse) ProtoMessage()    {}
func (*PeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_1b1d20431b205818, []int{1}
}
func (m *PeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerResponse.Unmarshal(m, b)
}
func (m *PeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerResponse.Marshal(b, m, deterministic)
}
func (dst *PeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerResponse.Merge(dst, src)
}
func (m *PeerResponse) XXX_Size() int {
	return xxx_messageInfo_PeerResponse.Size(m)
}
func (m *PeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerResponse proto.InternalMessageInfo

func (m *PeerResponse) GetPeers() []byte {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *PeerResponse) GetLocalPeers() []byte {
	if m != nil {
		return m.LocalPeers
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerRequest)(nil), "PeerRequest")
	proto.RegisterType((*PeerResponse)(nil), "PeerResponse")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_schema_1b1d20431b205818) }

var fileDescriptor_schema_1b1d20431b205818 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcc, 0x31, 0x0e, 0xc2, 0x30,
	0x0c, 0x05, 0x50, 0xa5, 0xc0, 0x62, 0xc2, 0x12, 0x31, 0x64, 0x42, 0x51, 0xa6, 0x4e, 0xdc, 0x01,
	0x89, 0x03, 0x54, 0xd9, 0x18, 0xab, 0xf6, 0x4b, 0x0c, 0x85, 0x04, 0x3b, 0x0c, 0xdc, 0x1e, 0xc5,
	0x5d, 0x60, 0xfb, 0x7e, 0xdf, 0x36, 0x59, 0x99, 0xee, 0x78, 0x8c, 0xe7, 0xc2, 0xb9, 0xe6, 0x78,
	0xa3, 0xfd, 0x00, 0x70, 0xc2, 0xeb, 0x0d, 0xa9, 0xce, 0xd1, 0xb6, 0x7e, 0x0a, 0xbc, 0x09, 0x5d,
	0x7f, 0x48, 0x9a, 0x9b, 0x95, 0xcc, 0xd5, 0x77, 0xc1, 0x34, 0x6b, 0xd9, 0x45, 0xb2, 0x4b, 0x9e,
	0xc6, 0xe5, 0x32, 0xcf, 0x0c, 0x11, 0xbf, 0x09, 0xa6, 0xb7, 0xe9, 0xcf, 0xe2, 0x95, 0xec, 0xfa,
	0x5a, 0x4a, 0x7e, 0x0a, 0xdc, 0x91, 0x76, 0x05, 0x60, 0xf1, 0x46, 0x97, 0xd7, 0xc1, 0x9d, 0x88,
	0xf4, 0x6a, 0xd0, 0xaa, 0xd3, 0xea, 0x47, 0xbe, 0x01, 0x00, 0x00, 0xff, 0xff, 0x14, 0x81, 0xfb,
	0x58, 0xaf, 0x00, 0x00, 0x00,
}
