// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: rpc-schema.proto

package protoschemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command         *string `protobuf:"bytes,1,req,name=command" json:"command,omitempty"`
	Id              []byte  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Target          []byte  `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	ForwardRequest  []byte  `protobuf:"bytes,4,opt,name=forwardRequest" json:"forwardRequest,omitempty"`
	ForwardResponse []byte  `protobuf:"bytes,5,opt,name=forwardResponse" json:"forwardResponse,omitempty"`
	RoundtripToken  []byte  `protobuf:"bytes,6,opt,name=roundtripToken" json:"roundtripToken,omitempty"`
	Value           []byte  `protobuf:"bytes,7,opt,name=value" json:"value,omitempty"`
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_rpc_schema_proto_rawDescGZIP(), []int{0}
}

func (x *RpcRequest) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

func (x *RpcRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RpcRequest) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RpcRequest) GetForwardRequest() []byte {
	if x != nil {
		return x.ForwardRequest
	}
	return nil
}

func (x *RpcRequest) GetForwardResponse() []byte {
	if x != nil {
		return x.ForwardResponse
	}
	return nil
}

func (x *RpcRequest) GetRoundtripToken() []byte {
	if x != nil {
		return x.RoundtripToken
	}
	return nil
}

func (x *RpcRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             []byte `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Nodes          []byte `protobuf:"bytes,2,opt,name=nodes" json:"nodes,omitempty"`
	Value          []byte `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	RoundtripToken []byte `protobuf:"bytes,4,opt,name=roundtripToken" json:"roundtripToken,omitempty"`
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_rpc_schema_proto_rawDescGZIP(), []int{1}
}

func (x *RpcResponse) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RpcResponse) GetNodes() []byte {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RpcResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RpcResponse) GetRoundtripToken() []byte {
	if x != nil {
		return x.RoundtripToken
	}
	return nil
}

var File_rpc_schema_proto protoreflect.FileDescriptor

var file_rpc_schema_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x0a, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x66, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x66,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x74, 0x72,
	0x69, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x74, 0x72, 0x69, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x71, 0x0a, 0x0b, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x74, 0x72, 0x69, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x74, 0x72, 0x69,
	0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73,
}

var (
	file_rpc_schema_proto_rawDescOnce sync.Once
	file_rpc_schema_proto_rawDescData = file_rpc_schema_proto_rawDesc
)

func file_rpc_schema_proto_rawDescGZIP() []byte {
	file_rpc_schema_proto_rawDescOnce.Do(func() {
		file_rpc_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_schema_proto_rawDescData)
	})
	return file_rpc_schema_proto_rawDescData
}

var file_rpc_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_schema_proto_goTypes = []interface{}{
	(*RpcRequest)(nil),  // 0: RpcRequest
	(*RpcResponse)(nil), // 1: RpcResponse
}
var file_rpc_schema_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_schema_proto_init() }
func file_rpc_schema_proto_init() {
	if File_rpc_schema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_schema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_schema_proto_goTypes,
		DependencyIndexes: file_rpc_schema_proto_depIdxs,
		MessageInfos:      file_rpc_schema_proto_msgTypes,
	}.Build()
	File_rpc_schema_proto = out.File
	file_rpc_schema_proto_rawDesc = nil
	file_rpc_schema_proto_goTypes = nil
	file_rpc_schema_proto_depIdxs = nil
}
