// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package dhtRpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Command              *string  `protobuf:"bytes,1,req,name=command" json:"command,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Target               []byte   `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	ForwardRequest       []byte   `protobuf:"bytes,4,opt,name=forwardRequest" json:"forwardRequest,omitempty"`
	ForwardResponse      []byte   `protobuf:"bytes,5,opt,name=forwardResponse" json:"forwardResponse,omitempty"`
	RoundtripToken       []byte   `protobuf:"bytes,6,opt,name=roundtripToken" json:"roundtripToken,omitempty"`
	Value                []byte   `protobuf:"bytes,7,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_b5424ed5eeada91e, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func (m *Request) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Request) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Request) GetForwardRequest() []byte {
	if m != nil {
		return m.ForwardRequest
	}
	return nil
}

func (m *Request) GetForwardResponse() []byte {
	if m != nil {
		return m.ForwardResponse
	}
	return nil
}

func (m *Request) GetRoundtripToken() []byte {
	if m != nil {
		return m.RoundtripToken
	}
	return nil
}

func (m *Request) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Response struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Nodes                []byte   `protobuf:"bytes,2,opt,name=nodes" json:"nodes,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	RoundtripToken       []byte   `protobuf:"bytes,4,opt,name=roundtripToken" json:"roundtripToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_b5424ed5eeada91e, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Response) GetNodes() []byte {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Response) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Response) GetRoundtripToken() []byte {
	if m != nil {
		return m.RoundtripToken
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_schema_b5424ed5eeada91e) }

var fileDescriptor_schema_b5424ed5eeada91e = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x4f, 0x4e, 0x87, 0x30,
	0x10, 0x85, 0xd3, 0xfe, 0xf8, 0xa3, 0x13, 0x82, 0x49, 0x43, 0xcc, 0x2c, 0x09, 0x0b, 0xc3, 0xca,
	0xc3, 0x10, 0x2f, 0xd0, 0xd0, 0x51, 0x89, 0xd2, 0xc1, 0xb6, 0xe8, 0x61, 0xbd, 0x8c, 0xb1, 0x45,
	0x54, 0xc2, 0xf2, 0x7d, 0x33, 0xf9, 0xf2, 0x1e, 0x54, 0x7e, 0x7c, 0xa6, 0x59, 0xdf, 0x2f, 0x8e,
	0x03, 0x77, 0x9f, 0x02, 0xca, 0x81, 0xde, 0x56, 0xf2, 0x41, 0x21, 0x94, 0x23, 0xcf, 0xb3, 0xb6,
	0x06, 0x45, 0x2b, 0xfb, 0xeb, 0xe1, 0x27, 0xaa, 0x1a, 0xe4, 0x64, 0x50, 0xb6, 0xa2, 0xaf, 0x06,
	0x39, 0x19, 0x75, 0x0b, 0x45, 0xd0, 0xee, 0x89, 0x02, 0x5e, 0x22, 0xdb, 0x92, 0xba, 0x83, 0xfa,
	0x91, 0xdd, 0x87, 0x76, 0x66, 0x73, 0x62, 0x16, 0xef, 0x07, 0xaa, 0x7a, 0xb8, 0xd9, 0x89, 0x5f,
	0xd8, 0x7a, 0xc2, 0x3c, 0x3e, 0x1e, 0xf1, 0xb7, 0xd1, 0xf1, 0x6a, 0x4d, 0x70, 0xd3, 0xf2, 0xc0,
	0x2f, 0x64, 0xb1, 0x48, 0xc6, 0xff, 0x54, 0x35, 0x90, 0xbf, 0xeb, 0xd7, 0x95, 0xb0, 0x8c, 0xe7,
	0x14, 0x3a, 0x0b, 0x57, 0xbb, 0x29, 0x6d, 0x10, 0xfb, 0x86, 0x06, 0x72, 0xcb, 0x86, 0xfc, 0x36,
	0x2b, 0x85, 0x5f, 0xcf, 0xe5, 0x8f, 0xe7, 0xa4, 0x45, 0x76, 0xd6, 0xe2, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x53, 0x09, 0x74, 0x99, 0x5c, 0x01, 0x00, 0x00,
}
